### ISSUE TITLE
Front page options

### ISSUE THREAD

**Issue by jeremyharris** [rockharbor/rockharbor#40]
Add a front page setting to either have the front page expand all widgets full width (global site), split into two columns (campus sites), or stack like [masonry](https://github.com/desandro/masonry). This would eliminate the need for the global site's front page template, as well as add a nice new options (masonry). If two column was selected, it would create another front page widget area for the second column.

This change would also require the need of a new "Blog" widget to show the blog posts as they are currently on the campuses. An optional widget could be a "Homepage Content" widget which would give campuses the ability to add a customized experience to the home page.

**Comment by scj1091** [comment]
The blog has been removed, so this issue is no longer relevant.
