### ISSUE TITLE
Change message pointers

### ISSUE THREAD

**Issue by jeremyharris** [rockharbor/rockharbor#56]
Currently the messages have two meta elements, `video_url` and `audio_url` which point directly to an S3 resource. It is then converted to an HTTP or RTMP Cloudfront URL.

The pointers should be stored in a single `media_path` meta field and accept a path (sans-extension), such as `/fullerton/files/2013/06/20130623_fullerton_message`.

This would allow greater flexibility when constructing the URL for the video player as well as give us the ability to easily add support for future encodings (see rockharbor/encoding-server#2).

**Comment by scj1091** [comment]
The file name is not always the same for different versions. Won't fix.
